name: apptacc
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0
  another_flutter_splash_screen:
  introduction_screen: ^3.1.8 #https://pub.dev/packages/introduction_screen
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  dio: ^4.0.4
  cupertino_icons: ^1.0.4
  provider: ^6.0.5
  google_maps_flutter: ^2.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Intro
      fonts:
        - asset: fonts/intro.otf
  assets: 
    - assets/images/
